.\" Manpage for jtoh.
.\" https://man7.org/linux/man-pages/man7/man-pages.7.html

.TH "JTOH" "1" "1st June 2022" "Linux" "JSONx to HTML"
.SH NAME
jtoh \- parse JSONx files into sintactically valid XHTML files
.SH SYNOPSIS
jtoh JSONx_FILE [ARG]...
.SH DESCRIPTION
jtoh parses JSONx files to produce sintactically XHTML files. JSONx scripts - that is, constrained JSON files - represent condensed XHTML code. JSONx scripts are parsed and used to generate dinamic XHTML code. JSONx has at least the same expressive power as XHTML, as proven in the assignment, and provides flow-control operations to create XHTML code on the go. 

.SH JSONx SYNTAX
*Escribir reglas de sintaxis JSONx*

.SH AUTHORS
Camila Di Toro (cditoro@itba.edu.ar)
Gonzalo Beade (gbeade@itba.edu.ar)
Salvador Castagnino (scastagnino@itba.edu.ar)


